### ISSUE TITLE
MUSHAR-toolbox_no file created in abs folder

### ISSUE THREAD

**Issue by HEL729242973** [bartbols/MUSHAR-toolbox#1] opened 2024-03-28 06:41 UTC
Dear Bart! 

My name is Yang Song from the Hong Kong Polytechnic University. I am working on a muscle shape project, and I found your MUSHAR Matlab tools. 🙂

I followed your instructions and installed and made available in the enviromental variables's path both the shapeworks (6.2.1) and the elastix (4.7) as well. The first script run without any error message and do the signed distancemaps files however it does not create the absolute distanmaps. The abs folder is empty where the second script wants to read the files. 

I only try with the example files so far but I don't know what could be the problem. Because no error message appears and debugging also didn't reveal the problem I cannot be more specific. May I ask your help about this problem? If you have any suggestions I would appreciate it very much!
![abs](https://github.com/bartbols/MUSHAR-toolbox/assets/122632739/2de5f519-c53b-4066-abf6-a09dccb9ce53)

**Comment by bartbols** [comment] 2024-04-08 22:45
Hi,
I think the problem is that you haven't installed Convert 3D, which is used to create the absolute distance maps from the signed distance map created by Shapeworks. I forgot to add that to the documentation - my bad.

You can download Convert3D here. Like with ShapeWorks and Elastix, make sure it's made available in your environment so that the command "c3d" is recognized.
http://www.itksnap.org/pmwiki/pmwiki.php?n=Downloads.C3D

Let me know if that solves the problem so that I can close the issue.
Bart

**Comment by HEL729242973** [comment] 2024-04-10 07:18
Dear Bart,
Hi, thank you for your kind help. It works very well after installing the Convert 3D.
Thanks again!
Yang

===============================
With Regards,
宋 杨/Song Yang, PhD
Department of Biomedical Engineering
Faculty of Engineering
The Hong Kong Polytechnic University
T1: (86) 132 9686 6869
T2: (852) 5449 2107
E: ***@***.***
https://www.polyu.edu.hk/bme
===============================



________________________________
发件人: Bart Bolsterlee ***@***.***>
发送时间: Tuesday, April 9, 2024 6:46:03 AM
收件人: bartbols/MUSHAR-toolbox ***@***.***>
抄送: HEL729242973 ***@***.***>; Author ***@***.***>
主题: Re: [bartbols/MUSHAR-toolbox] MUSHAR-toolbox_no file created in abs folder (Issue #1)


Hi,
I think the problem is that you haven't installed Convert 3D, which is used to create the absolute distance maps from the signed distance map created by Shapeworks. I forgot to add that to the documentation - my bad.

You can download Convert3D here. Like with ShapeWorks and Elastix, make sure it's made available in your environment so that the command "c3d" is recognized.
http://www.itksnap.org/pmwiki/pmwiki.php?n=Downloads.C3D

Let me know if that solves the problem so that I can close the issue.
Bart

―

**Closed as completed** 2024-07-09 00:07 UTC
